baseurl = "https://jmanuelrosa.github.io/federicapiccinini/"
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "hugo-creative-theme"
googleAnalytics = "UA-138971999-1"
publishDir = "docs"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Federica Piccinini"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Building bridges"
		subtitle   = "\"Translation is not a matter of words only; it is a matter of making intelligible a whole culture.\" Anthony Burgess"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Who am I?"
		description = "I'm Federica Piccinini, a native Italian translator and language lover! With experience in translation and localization, I'll be glad to help you share your ideas with the world! "
		buttonText  = "Know me better!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Translation and localization"
            description = "Do you want to go beyond the words and translate the ideas? Use the power of localization!"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Proofreading"
			description = "Make sure your text is fluid and error-free!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Private classes"
            description = "Do you want to learn or improve your English, Spanish or Italian? You're in the right place!"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Multi-language websites and blogs"
            description = "You don't need to look for a developer, a web designer and a translator: here you have a single solution!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to take the next step? That's great! Give me a call or send me an email and I'll get back to you as soon as possible!"
		phone = "+39 3397331360"
		email = "federicapiccinini6@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
